name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20
        
        - name: Publish releases mac x64
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: matrix.os == 'macos-13'
              run: npm exec electron-builder -- --mac dmg zip --x64 --publish onTagOrDraft

            - name: Publish releases mac arm64
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: matrix.os == 'macos-14'
              run: npm exec electron-builder -- --mac dmg zip --arm64 --publish onTagOrDraft

            - name: Publish releases windows
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: matrix.os == 'windows-latest'
              run: npm exec electron-builder -- --publish onTagOrDraft

            - name: Publish releases GNU Linux x64
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: matrix.os == 'ubuntu-22.04'
              run: npm exec electron-builder -- --linux deb rpm tar.xz --x64 --publish onTagOrDraft

            - name: Publish releases GNU Linux arm64
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: matrix.os == 'ubuntu-24.04'
              run: npm exec electron-builder -- --linux deb rpm tar.xz --arm64 --publish onTagOrDraft
